# Full path to use for LevelDb Database
databasepath="/etc/nsnitch/responses.db"
# Number of seconds to cache records for
databasettl=300

# Pull path to module configuration files
includepath="/etc/nsnitch/conf.d"

# MaxMind Key for GeoIP download
# Only necessary if you're using an NSnitch module
#maxmindkey="LICENSE_KEY"
#geodbpath="/etc/nsnitch/geo.db"

# Url for Tor Updates
torurl="https://check.torproject.org/exit-addresses"

# Port Settings
defaulthttpport=80
defaulthttpsport=443
defaultdnsudpport=53
defaultdnstcpport=53
defaultdnstlsport=853

# bgp settings
# Only necessary if you're using BGP
#[peers]
#    [peer.example]
#    localas=396093
#    localip="10.0.0.1"
#    peeras=6500
#    peerip="1.2.3.4"
#    peerpassword="secret"

# BGP Advertisement blocks
# Only necessary if you're using BGP
#[netblocks]
#    [netblock]
#    ip="10.1.0.0"
#    netmask="24"
    # set to true in order to force announcing this range, even if no
    # configured mofule requires it
    #force=false
#    [netblocks]
#    ip="192.168.1.0"
#    netmask="24"

# Lookup Credentials allow for Executing Lookups against the API
threadedresolver=false
[lookupcreds]
"ABC"="123"
"XYZ"="456"

# Admin Credentials allow for Controlling Tenta DNS
[admincreds]
"ABC"="789"
"XYZ"="012"